apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    name: first-app
spec:
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
  selector:
    matchLabels:
      app: first-app
  
  replicas: 7