apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    name: my-app
spec:
  template:
    metadata:
      labels:
        app: my-app
      namespace: devops
    spec:
      containers:
        - name: container-1
          image: httpd:latest
          ports:
          - name: http
            containerPort: 80
  selector:
    app: my-app
    
  replicas: 7