apiVersion: v1
kind: Pod
metadata: 
  name: mayur-pod 
  labels:
    app: my-app
  namespace: devops
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - name: http
          containerPort: 80