apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx:latest
      Ports:
        - name: http
          containerPort: 80